### ISSUE TITLE
Fail fast on creating mutations that cannot be stored

### ISSUE THREAD

**Issue by alugowski** [googleapis/java-bigtable-hbase#1919]
This is in the context of Beam `CloudBigtableIO`. The client has a bulk mutation limit of 100k. As of #1497 this means as long as each individual `Put` is under that limit everything will be fine.

A Dataflow job can have large variability in the amount of data per row. It is also natural to write `processElement` using a single `Put`, especially since that is what the examples guide new users to do.

If a single `Put` is larger than 100k mutations then it is impossible to store. The exception it causes is thrown later, and from a different thread.

The client should throw the TooManyMutations exception much earlier, preferably so the user code that caused the 100001th mutation it is still in the stack trace.

**Comment by alugowski** [comment]
Example stack trace below.

```
com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Too many mutations: 182076 provided; limit 100000
	at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onError(AbstractRetryingOperation.java:228)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onClose(AbstractRetryingOperation.java:193)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.ThrottlingClientInterceptor$1$1.onClose(ThrottlingClientInterceptor.java:98)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(ChannelPool.java:210)
	at com.google.bigtable.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$UnAuthResponseListener.onClose(RefreshingOAuth2CredentialsInterceptor.java:85)
	at com.google.bigtable.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.bigtable.repackaged.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
	at com.google.bigtable.repackaged.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at com.google.bigtable.repackaged.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at com.google.bigtable.repackaged.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:403)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:459)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:546)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:467)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:584)
	at com.google.bigtable.repackaged.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.google.bigtable.repackaged.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sduskis** [comment]
We definitely show throw exceptions earlier.  We can also add an option (with a big Caveat Emptor) to allow multiple Puts in this case.

**Comment by sduskis** [comment]
@alugowski, did this relate to the [import](https://cloud.google.com/bigtable/docs/importing-sequence-files) job, or was there some other situation that needed to be addressed?

**Comment by alugowski** [comment]
@sduskis no, our context is a Dataflow job that copies a BigQuery result into BigTable.

Our job closely resembled the BigQueryBigtableTransfer example. Many datasets have many columns in a CF. If someone were to use a query with more than 100k columns in a single BigQuery result row then you'd hit the case I'm describing.

https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/dataflow-connector-examples/src/main/java/com/google/cloud/bigtable/dataflow/example/BigQueryBigtableTransfer.java

**Comment by sduskis** [comment]
@alugowski, we're prototyping an implementation that would technically solve your issue, but we're not convinced that it's the right thing to do in our library.  Since you have control over your DoFn, you can create multiple `Put` objects that only have 100K columns rather than having the library do it for you.  That ought to solve your problem relatively simply compared to a library change.  What do you think?

**Comment by alugowski** [comment]
@sduskis Of course, that's exactly what we did a month ago to move forward. 

I opened this issue not for myself but for future new users who will follow the examples and get bitten by a mystery error.

I'm only requesting throwing the error where it's easy to debug. I can imagine the fix will be a single `if` statement around `addColumn()`. An automatic split into multiple `Put`s would simplify client code, but I understand why it might be difficult or impossible to do safely.

It would be helpful to update the BigQueryBigtableTransfer example as well to show what your team feels best practice looks like.

**Comment by sduskis** [comment]
@alugowski, thanks for the context.

FYI, `Put` is owned by HBase, which doesn't have the 100K limitation, so we couldn't add an exception there.  We added the warning in our implementation of `BufferedMutator.mutate`, which is called under the cover in `CloudBigtableIO`. 

We were exploring possibilities of how to improve the experience.  A note in `BigQueryBigtableTransfer` would help.  We may also fix our [import](https://cloud.google.com/bigtable/docs/importing-sequence-files) job, where users can't control the code themselves.
