### ISSUE TITLE
Use GetTable for Admin.tableExists

### ISSUE THREAD

**Issue by sduskis** [googleapis/java-bigtable-hbase#2016]
It turns out that there's a server-side bug in `GetTable` that returns false results for a table that was recently deleted.  Here's the plan:

- [x] revert #1980 
- [ ] fix the server-side issue
- [ ] restore #1980

**Comment by rahulKQL** [comment]
Additional Info: `BigtableAsyncAdmin#listTable` was falling into `FAILED_PRECONDITION` Or `NOT_FOUND` when trying to full `Table` details using `getTableAsync` for each tableID received from `listTableAsync`. 
I believe this bug is related([discussion on the same](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/2095#discussion_r256114592)).

**Comment by rahulKQL** [comment]
## Observations

This issue is consistent for both `bigtable-client-core` & `GCJ-Veneer` client. It can be quickly recreated by updating `BigtableAsyncAdmin#listTables`:
```java
  private CompletableFuture<List<TableDescriptor>> listTables(Optional<Pattern> tableNamePattern) {
    return listTableNames(tableNamePattern)
        .thenApply(
            list ->
                list.stream()
                    .map(t -> getDescriptor(t).join())
                    .collect(Collectors.toList()));
  }
```

This throws below exception from `TestAsyncAdmin#testCreateTable_harness` method. Unfortunately, This same test pass successfully when run in IDE.

```sh
java.util.concurrent.ExecutionException: org.apache.hadoop.hbase.TableNotFoundException: test_table2-0000016b325d6419-bffb226ebb9c40de
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.google.cloud.bigtable.hbase.async.TestAsyncAdmin.testCreateTable_harness(TestAsyncAdmin.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.hadoop.hbase.TableNotFoundException: test_table2-0000016b325d6419-bffb226ebb9c40de
	at com.google.cloud.bigtable.hbase2_x.BigtableAsyncAdmin.lambda$getDescriptor$12(BigtableAsyncAdmin.java:277)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at com.google.cloud.bigtable.hbase2_x.FutureUtils$2.onFailure(FutureUtils.java:55)
	at com.google.bigtable.repackaged.com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:68)
	at com.google.bigtable.repackaged.com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1070)
	at com.google.bigtable.repackaged.com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:30)
	at com.google.bigtable.repackaged.com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1139)
```

**Comment by igorbernstein** [comment]
just to make sure I understand is this  the scenario?

1. A table is deleted
2. List tables returns the id of the table
3. Calling get table throws a not found exception

**Comment by sduskis** [comment]
The test creates tables and runs list tables at the same time in asynchronously running tests.  `ListTables` can return tables that are not completely ready yet, and calling `GetTable` on one of those table names will result in `NotFound`

**Comment by igorbernstein2** [comment]
re: ListTables
I think we should just catch the NotFound errors from GetTable and remove those entries from the list

**Comment by rahulKQL** [comment]
Just wanted to add this: Currently `BigtableAsyncAdmin#listTables` [works fine(It returns name only TableDescriptor)](https://github.com/googleapis/cloud-bigtable-client/blob/master/bigtable-hbase-2.x-parent/bigtable-hbase-2.x/src/main/java/com/google/cloud/bigtable/hbase2_x/BigtableAsyncAdmin.java#L230). This problem arises when fetching the full `TableDescriptor`.
I think we should continue with name only descriptor instead of removing entries from the list.
@igorbernstein2  Let me know your thought on this.

**Comment by irvifa** [comment]
Hi is this already implemented in the current release?

**Comment by rahulKQL** [comment]
@irvifa Unfortunately we have yet to implement this. This is more related to internal changes and may take some time before we focus on it.
