### ISSUE TITLE
Errors creating sequenceFile to bigTable template.

### ISSUE THREAD

**Issue by sethwilsonATI** [googleapis/java-bigtable-hbase#2373]
Hello,

I'm trying to create a template from bigtable-beam-import for importing data from a SequenceFile into BigTable.

My command is as follows:

`mvn compile exec:java -DmainClass=com.google.cloud.bigtable.beam.sequencefiles.ImportJob -Dexec.args="--runner=DataFlowRunner --project=<projectName> --templateLocation=gs://path/to/templateFile --maxNumWorkers=10 --diskSizeGb=60"`

When I first ran this in the latest version of this repo, I received an error that maven couldn't find the `1.13.1-SNAPSHOT` dependency. So I changed the version to `1.13.0` in the POM, since that's the latest version I see in Maven. Running the command now generates various errors.

This seems to be the main error:

```
2020-01-28 11:03:56 INFO  DataflowRunner:887 - Template successfully created.
2020-01-28 11:03:56 WARN  Utils:89 - Unable to wait for pipeline to finish.
java.lang.UnsupportedOperationException: The result of template creation should not be used.
        at org.apache.beam.runners.dataflow.util.DataflowTemplateJob.getState(DataflowTemplateJob.java:67)
        at com.google.cloud.bigtable.beam.sequencefiles.Utils.waitForPipelineToFinish(Utils.java:81)
        at com.google.cloud.bigtable.beam.sequencefiles.ImportJob.main(ImportJob.java:148)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

Along with, perhaps, this one:

```
java.lang.IllegalStateException: Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider{propertyName=sourcePattern, default=null}
        at org.apache.beam.sdk.options.ValueProvider$RuntimeValueProvider.get(ValueProvider.java:226)
        at org.apache.beam.sdk.io.FileBasedSource.getEstimatedSizeBytes(FileBasedSource.java:219)
        at com.google.cloud.bigtable.beam.sequencefiles.ShuffledSource.getEstimatedSizeBytes(ShuffledSource.java:57)
        at org.apache.beam.runners.dataflow.internal.CustomSources.serializeToCloudSource(CustomSources.java:77)
        at org.apache.beam.runners.dataflow.ReadTranslator.translateReadHelper(ReadTranslator.java:51)
        at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:38)
        at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:35)
        at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:473)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:665)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
        at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:317)
        at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:251)
        at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:460)
        at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:412)
        at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:173)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:748)
        at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:179)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
        at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
        at com.google.cloud.bigtable.beam.sequencefiles.ImportJob.main(ImportJob.java:145)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

Even though, as you can see, I'm not using `sourcePattern` in my arguments. Maybe I should? But I'd rather do this dynamically at runtime.

And also various errors/warnings about threading.

The build still says it's successful, but no template is generated in my specified storage bucket.

Here's my Maven/Java version, perhaps that's the issue?

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\maven\bin\..
Java version: 13.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13.0.2
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

Forgive my ignorance--Java isn't really my strong suit. Really the only reason I'm doing this is because the SequenceFile to BigTable template provided by Google only has a disk size of 25GB and I'm getting disk space errors on jobs. If you have suggestions for specifying disk space through the API, without the need to compile a template, that'd also be appreciated.

Thanks so much for your help!

**Comment by rahulKQL** [comment]
@sethwilsonATI Thanks for reporting the issue, I have tried to answer your queries.

> When I first ran this in the latest version of this repo, I received an error that maven couldn't find the 1.13.1-SNAPSHOT dependency.

 Please run `mvn clean package` to build the latest version of jars in your local machine.

--
  

> ```sh
> 2020-01-28 11:03:56 WARN  Utils:89 - Unable to wait for pipeline to finish.
>  java.lang.UnsupportedOperationException: The result of template creation should not be used.
> ```

 While creating a template [wait](https://github.com/googleapis/java-bigtable-hbase/blob/4959c8f0ca119e19a7585875ba056934dda60957/bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/ImportJob.java#L128-L130) is not supported. However it doesn't stop the current execution, it simply logs the error. you can find it here.
https://github.com/googleapis/java-bigtable-hbase/blob/4959c8f0ca119e19a7585875ba056934dda60957/bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/Utils.java#L77-L91 
    Meaning this is unrelated to your templates not being generated.

--

>  I'm not using sourcePattern in my arguments. Maybe I should? But I'd rather do this dynamically at runtime.

 The `sourcePattern` points to the sequenceFiles files patterns exported in the storage. 
https://github.com/googleapis/java-bigtable-hbase/blob/4959c8f0ca119e19a7585875ba056934dda60957/bigtable-dataflow-parent/bigtable-beam-import/src/main/java/com/google/cloud/bigtable/beam/sequencefiles/ImportJob.java#L113-L115
It is ok to not provide sourcePattern right away, your templates generation should not be affected.
  
--

> And also various errors/warnings about threading.

I think you may observe below warnings in the log, If you see any thread related issues in the log could you please add it here I'll have a look.
```
2020-02-01 00:46:36 WARN  DataflowRunner:243 - --region not set; 
...
2020-02-01 00:46:40 WARN  RetryHttpRequestInitializer:159 - Request failed with code 409, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes, HTTP framework says request can be retried, (caller responsible for retrying)
```

--

> I'm doing this is because the SequenceFile to BigTable template provided by Google only has a disk size of 25GB and I'm getting disk space errors on jobs. If you have suggestions for specifying disk space through the API, without the need to compile a template, that'd also be appreciated.

I am not confident if it will work or not, but try giving the `diskSizeGb` flag in your dataflow jobs experiment block. for eg. `--diskSizeGb=80`.
![dataflow_configs](https://user-images.githubusercontent.com/42969463/73574090-d6588800-449a-11ea-8b8c-f1db237aef49.png)
