### ISSUE TITLE
Value only available at runtime, but accessed from a non-runtime context

### ISSUE THREAD

**Issue by czka** [googleapis/java-bigtable-hbase#2389]
[bigtable-beam-import-1.13.0-shaded.jar](https://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-beam-import/1.13.0/bigtable-beam-import-1.13.0-shaded.jar) returns a  `java.lang.IllegalStateException: Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider{propertyName=bigtableStartRow, default=}` error for each `export` operation which doesn't have ` --bigtableStartRow` set:

```
(...)
2020-02-24 15:49:06 INFO  DataflowPipelineTranslator:522 - Adding Read table as step s1
2020-02-24 15:49:06 WARN  CustomSources:79 - Size estimation of the source failed: com.google.cloud.bigtable.beam.CloudBigtableIO$Source@5528a42c
java.lang.IllegalStateException: Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider{propertyName=bigtableStartRow, default=}
	at org.apache.beam.sdk.options.ValueProvider$RuntimeValueProvider.get(ValueProvider.java:226)
	at com.google.cloud.bigtable.beam.TemplateUtils$RequestValueProvider.get(TemplateUtils.java:95)
	at com.google.cloud.bigtable.beam.TemplateUtils$RequestValueProvider.get(TemplateUtils.java:76)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration$RequestWithTableNameValueProvider.get(CloudBigtableScanConfiguration.java:275)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration$RequestWithTableNameValueProvider.get(CloudBigtableScanConfiguration.java:253)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getRequest(CloudBigtableScanConfiguration.java:330)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getRowRange(CloudBigtableScanConfiguration.java:362)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getStartRowByteString(CloudBigtableScanConfiguration.java:354)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getZeroCopyStartRow(CloudBigtableScanConfiguration.java:345)
	at com.google.cloud.bigtable.beam.CloudBigtableIO$Source.getEstimatedSizeBytes(CloudBigtableIO.java:461)
	at org.apache.beam.runners.dataflow.internal.CustomSources.serializeToCloudSource(CustomSources.java:77)
	at org.apache.beam.runners.dataflow.ReadTranslator.translateReadHelper(ReadTranslator.java:51)
	at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:38)
	at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:35)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:473)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:665)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:317)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:251)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:460)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:412)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:173)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:748)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:179)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.main(ExportJob.java:181)
	at com.google.cloud.bigtable.beam.sequencefiles.Main.main(Main.java:41)
2020-02-24 15:49:06 INFO  DataflowPipelineTranslator:522 - Adding Format results/Map as step s2
(...)
```

To reproduce try running:
```
java -jar bigtable-beam-import-1.13.0-shaded.jar export --runner=dataflow --project=<project-name> --destinationPath=gs://<bucket-name> --bigtableInstanceId=<instance-name> --bigtableTableId=<table-id> --tempLocation=gs://<bucket-name>/temp --maxNumWorkers=1 --diskSizeGb=30 --workerMachineType=n1-standard-1 --jobName=<job-name> --region=<region-name> --sdkWorkerParallelism=0 --bigtableMaxVersions=1
```

When `--bigtableStartRow` is set, it complains about `bigtableStopRow` for a change:

```
(...)
2020-02-24 16:03:57 INFO  DataflowPipelineTranslator:522 - Adding Read table as step s1
2020-02-24 16:03:57 WARN  CustomSources:79 - Size estimation of the source failed: com.google.cloud.bigtable.beam.CloudBigtableIO$Source@54ec8cc9
java.lang.IllegalStateException: Value only available at runtime, but accessed from a non-runtime context: RuntimeValueProvider{propertyName=bigtableStopRow, default=}
	at org.apache.beam.sdk.options.ValueProvider$RuntimeValueProvider.get(ValueProvider.java:226)
	at com.google.cloud.bigtable.beam.TemplateUtils$RequestValueProvider.get(TemplateUtils.java:98)
	at com.google.cloud.bigtable.beam.TemplateUtils$RequestValueProvider.get(TemplateUtils.java:76)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration$RequestWithTableNameValueProvider.get(CloudBigtableScanConfiguration.java:275)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration$RequestWithTableNameValueProvider.get(CloudBigtableScanConfiguration.java:253)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getRequest(CloudBigtableScanConfiguration.java:330)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getRowRange(CloudBigtableScanConfiguration.java:362)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getStartRowByteString(CloudBigtableScanConfiguration.java:354)
	at com.google.cloud.bigtable.beam.CloudBigtableScanConfiguration.getZeroCopyStartRow(CloudBigtableScanConfiguration.java:345)
	at com.google.cloud.bigtable.beam.CloudBigtableIO$Source.getEstimatedSizeBytes(CloudBigtableIO.java:461)
	at org.apache.beam.runners.dataflow.internal.CustomSources.serializeToCloudSource(CustomSources.java:77)
	at org.apache.beam.runners.dataflow.ReadTranslator.translateReadHelper(ReadTranslator.java:51)
	at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:38)
	at org.apache.beam.runners.dataflow.ReadTranslator.translate(ReadTranslator.java:35)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.visitPrimitiveTransform(DataflowPipelineTranslator.java:473)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:665)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.visit(TransformHierarchy.java:657)
	at org.apache.beam.sdk.runners.TransformHierarchy$Node.access$600(TransformHierarchy.java:317)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:251)
	at org.apache.beam.sdk.Pipeline.traverseTopologically(Pipeline.java:460)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator$Translator.translate(DataflowPipelineTranslator.java:412)
	at org.apache.beam.runners.dataflow.DataflowPipelineTranslator.translate(DataflowPipelineTranslator.java:173)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:748)
	at org.apache.beam.runners.dataflow.DataflowRunner.run(DataflowRunner.java:179)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:315)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:301)
	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.main(ExportJob.java:181)
	at com.google.cloud.bigtable.beam.sequencefiles.Main.main(Main.java:41)
2020-02-24 16:03:57 INFO  DataflowPipelineTranslator:522 - Adding Format results/Map as step s2
(...)
```

**Comment by igorbernstein2** [comment]
Thanks for reporting!

We do need to fix this, but please note that this is only a cosmetic warning and can be ignored

**Comment by czka** [comment]
@igorbernstein2 I know it's non-fatal. Otheriwse my (bigtable_export.py)[https://github.com/egnyte/bigtable-backup-and-restore/blob/master/bigtable_export.py] wouldn't work ;).
