### ISSUE TITLE
beam export job leaks grpc connections

### ISSUE THREAD

**Issue by igorbernstein2** [googleapis/java-bigtable-hbase#2504]
Dataflow logs are filled with:

```
Channel ManagedChannelImpl{logId=3217, target=bigtableadmin.googleapis.com:443} was not shutdown properly!!! *~ Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
```
I'm guessing this is an issue with channel pool caching where the dataflow job reuses the same channel pool for data channels, but opens new ones for admin channels.

**Comment by dmitry-fa** [comment]
The same message appears in the log from running tests:
```
[INFO] Running com.google.cloud.bigtable.grpc.TestBigtableTableAdminGCJClient
Aug 18, 2020 11:47:27 AM com.google.cloud.bigtable.config.CredentialOptions info
INFO: Enabling the use of null credentials. This should not be used in production.
Aug 18, 2020 11:47:27 AM com.google.cloud.bigtable.config.BigtableVeneerSettingsFactory info
INFO: Enabling the use of null credentials. This should not be used in production.
Aug 18, 2020 11:47:27 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=166, target=bigtableadmin.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
        at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:518)
        at com.google.cloud.bigtable.grpc.BigtableSession.createNettyChannel(BigtableSession.java:630)
        at com.google.cloud.bigtable.grpc.BigtableSession.createInstanceClient(BigtableSession.java:778)
        at com.google.cloud.bigtable.grpc.TestBigtableSession.testCreateInstanceClient(TestBigtableSession.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        ...
```

I think that confusing message is due to the bug in the logger: https://github.com/googleapis/java-logging/issues/211 caused by not closing a channel in the `GrpcLoggingRpc`

**Comment by dmitry-fa** [comment]
@igorbernstein2 This message no longer appears in the test logs, so I closing this issue. Please reopen it if you meet this message somewhere else.

**Comment by dmitry-fa** [comment]
The same message appears in the tests for BigTable Hello World snippet.
```
Nov 09, 2020 11:51:08 AM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=39, target=bigtable.googleapis.com:443} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:596)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:261)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:340)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1600(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:236)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:243)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:226)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:169)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:128)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:161)
	at com.m.examples.bigtable.HelloWorld.<init>(HelloWorld.java:79)
	at com.m.examples.bigtable.HelloWorldTest.testCreateAndDeleteTable(HelloWorldTest.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
```

**Comment by dmitry-fa** [comment]
This might happen if a data or admin client is not closing properly.
In the Hello World snippet, the client created at:
```
78    // Creates a bigtable data client.
79    dataClient = BigtableDataClient.create(settings);
```
is never closed, quoting stack trace:

```
at com.m.examples.bigtable.HelloWorld.<init>(HelloWorld.java:79)
```

Note that the printed stack trace corresponds not the moment when `cleanQueue` method is invoked, but the instance when the client is created.

**Comment by kolea2** [comment]
@dmitry-fa going to close this here as this will be resolved by https://github.com/googleapis/java-bigtable/pull/516. If we see it elsewhere, let's raise a new issue in the java-bigtable repo for the samples. Thanks!
