### ISSUE TITLE
bigtable-hbase-2.x-hadoop. Cannot create an instance of Async Connection

### ISSUE THREAD

**Issue by Nivroc** [googleapis/java-bigtable-hbase#2830]
#### Environment details

1. Specify the API at the beginning of the title. General, Core, and Other are also allowed as types
2. OS type and version: Windows10
3. Java version: 1.8
4. Version(s): 1.18.0

#### Code example

```scala
val conf = BigtableConfiguration.asyncConfigure(BigtableConfiguration.configure(instanceId, projectId))
ConnectionFactory.createAsyncConnection(conf)
```

#### Stack trace
```
java.lang.RuntimeException: java.lang.RuntimeException: class org.apache.hadoop.hbase.client.BigtableAsyncRegistry not org.apache.hadoop.hbase.client.ConnectionRegistry
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2427)
	at org.apache.hadoop.hbase.client.ConnectionRegistryFactory.getRegistry(ConnectionRegistryFactory.java:38)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createAsyncConnection(ConnectionFactory.java:284)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createAsyncConnection(ConnectionFactory.java:263)
	at BigTable$$anon$1.getHbaseConnection(BigTable.scala:35)
```

#### Any additional information below
ConnectionFactory.java#CompletableFuture<AsyncConnection> createAsyncConnection(Configuration conf, final User user)
contains a line 
ConnectionRegistry registry = ConnectionRegistryFactory.getRegistry(conf);
I believe that should be
AsyncRegistry registry = AsyncRegistryFactory.getRegistry(conf);

Explanation: in docs to "BigtableAsyncRegistry" there is a reference to AsyncRegistryFactory, but it is never used anywhere in code and I don't see any other way to get an instance of AsyncRegistry:
```<p>This class is injected via the system property: "hbase.client.registry.impl" For further
 details See {@link AsyncRegistryFactory#REGISTRY_IMPL_CONF_KEY}, and {@link
 ConnectionFactory#createAsyncConnection()}
 ```
except ConnectionFactory#createAsyncConnection() doesn't use AsyncRegistryFactory

**Comment by Nivroc** [comment]
Make sure to use org.apache.hbase.shaded-client. It has this issue fixed.
